
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mariadb://127.0.0.1:${DB_PORT}/product-manager
    username: root
    password: ${PW}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
server:
  port: ${PORT}
