spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mariadb://localhost:3406/product-manager
    username: root
    password: ${PW}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
